plt.rcParams["figure.figsize"] = [6.03, 4.03]
plt.title("Learning Rate vs Train Step")
temp_learning_rate_schedule = CustomSchedule(128)
plt.plot(temp_learning_rate_schedule(tf.range(40000, dtype=tf.float32)))
temp_learning_rate_schedule = CustomSchedule(256)
plt.plot(temp_learning_rate_schedule(tf.range(40000, dtype=tf.float32)))
temp_learning_rate_schedule = CustomSchedule(512)
plt.plot(temp_learning_rate_schedule(tf.range(40000, dtype=tf.float32)))
temp_learning_rate_schedule = CustomSchedule(1024)
plt.plot(temp_learning_rate_schedule(tf.range(40000, dtype=tf.float32)))
plt.axvline(x=4000, color='k', linestyle='--')
plt.ylabel("Learning Rate")
plt.xlabel("Train Step")
plt.legend(["128", "256", "512", "1024", r"$warmup_{steps}$ = 4000"], title=r"$d_{model}$")